version: '3.8'

services:
  django:
    build: .
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    # depends_on:
    #   - db
    command: ["sh", "/app/entrypoint.sh"]

#   db:
#     image: postgres:15
#     container_name: postgres_db
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: mydatabase
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: